// Students/staff without a real email get one auto-generated by this app
// (create-student-auth-user / useStaffAuth's useActivateStaffLogin), always
// ending in "@{school-short-name}.ug" — a synthetic address nobody can
// actually receive mail at. Detecting that pattern client-side, before ever
// attempting an email-based password reset, lets the UI immediately steer a
// non-technical user toward the IT-admin-assisted fallback instead of
// silently sending them into a void with no signal anything's wrong.
//
// This does NOT leak whether any specific account exists — it only checks
// whether the typed address matches the school's own known, public
// auto-generation convention (same domain suffix for every such account),
// which is not sensitive information.
export function isPlaceholderSchoolEmail(email: string, schoolShortName: string | null): boolean {
  if (!schoolShortName) return false
  const domain = email.trim().toLowerCase().split('@')[1]
  if (!domain) return false
  const sanitizedShortName = schoolShortName.toLowerCase().replace(/[^a-z0-9]/g, '')
  if (!sanitizedShortName) return false
  return domain === `${sanitizedShortName}.ug`
}
