version: '3.8'

services:
  shule-app:
    image: ${SCHOOL_IMAGE_NAME:-shule-frontend}
    ports:
      - "80:80"
    restart: always
    networks:
      - shule-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-ShuleDB2025}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - shule-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  shule-network:
    driver: bridge

volumes:
  postgres_data:
